### ISSUE TITLE
support Hetzner DNS

### ISSUE THREAD

**Issue by ibotty** [openshift/external-dns-operator#170]
It would be great to allow managing zones hosted on Hetzner's DNS servers.  There is certmanager integration available in the plugin https://github.com/vadimkim/cert-manager-webhook-hetzner that might give hints on how to access the API.

**Comment by ibotty** [comment]
/lifecycle frozen
/remove-lifecycle stale

Would still be great to have.

**Comment by alebedev87** [comment]
Hello @ibotty!

Sorry for the late response. Hetzner DNS is not supported by [the upstream community](https://github.com/kubernetes-sigs/external-dns). It's very unlikely this new provider can end up in `ExternalDNS` API of the operator without the actual backup upstream.
There is an [initiative](https://github.com/kubernetes-sigs/external-dns/pull/3192) to re-add the support though.

**Comment by alebedev87** [comment]
Closing as not supported by the upstream project.
