### ISSUE TITLE
Expose pod nodeSelector in the CRD

### ISSUE THREAD

**Issue by roivaz** [openshift/external-dns-operator#214]
It would be nice if the field `spec.template.spec.nodeSelector` in the external-dns Deployment could be configurable by exposing this configuration via the ExternalDNS custom resource. 
I am using the external-dns-operator in a cluster provisioned via [hypershift](https://hypershift-docs.netlify.app). In this scenario the scheduler is unable to run external-dns pods because there are no master nodes available, so the pods stay in `pending` forever. The node selector is hardcoded [here](https://github.com/openshift/external-dns-operator/blob/67958439f2cdd11212687623f1dbf7328ca9916d/pkg/operator/controller/externaldns/deployment.go#L203-L206).
The workaround I'm appying is to remove the `node-role.kubernetes.io/master: ''` label from the nodeSelector in the Deployment object, as the operator seems to not reconcile this.

**Comment by alebedev87** [comment]
@roivaz: Yes, the current node selector cause a problem on HyperShift based deployments. Can you please file a bug for "ExternalDNS Operator" component?

**Comment by Miciah** [comment]
The feature request is now being tracked as [RFE-5408](https://issues.redhat.com/browse/RFE-5408)

**Comment by alebedev87** [comment]
@roivaz: https://github.com/openshift/external-dns-operator/pull/219 relaxes the node selector by removing the master label.

**Comment by roivaz** [comment]
@alebedev87  Thank you! That would definitely solve the issue. Any idea of the release this fix will be shipped in?

**Comment by alebedev87** [comment]
The deadline is the GA of OpenShift 4.17, so beginning of October. However this operator is off the main payload so it can be released earlier.

**Comment by alebedev87** [comment]
Closing the issue as [the reporter confirmed](https://github.com/openshift/external-dns-operator/issues/214#issuecomment-2270885508) https://github.com/openshift/external-dns-operator/pull/219 should fix the issue.
