### ISSUE TITLE
Can't scrape external-dns instance metrics

### ISSUE THREAD

**Issue by roivaz** [openshift/external-dns-operator#216]
Instance metrics in the operator managed external-dns pods are bound to `127.0.0.1:7979` and this doesn't seem to be configurable. Also, external-dns instance pods don't have the rbac proxy sidecar (which the operator pod has), so it's not possible to scrape the metrics from Prometheus through the sidecar either. I'm using version v1.2.0. 
Being able to scrape the metrics would be great :).

**Comment by roivaz** [comment]
It's just for a complete monitoring picture as you say. We have used external-dns without the operator for some time now and are switching to use the operator, so we were looking into reusing our existent alerts and dashboards. But we only have one external-dns instance, so our use case is much simpler in that regard.  
In the end we have decided that we can do without scrapping the external-dns instances, as the metrics it provides weren't too relevant for our service after all and we have many other ways to detect anomalies.

**Comment by alebedev87** [comment]
Closing the issue based on [the provided explanation](https://github.com/openshift/external-dns-operator/issues/216#issuecomment-2049527108) and the reporter's comment regarding [the irrelevant nature of the upstream metrics](https://github.com/openshift/external-dns-operator/issues/216#issuecomment-2049634728). If operand metrics are required, an RFE will need to be filed.
