### ISSUE TITLE
No MaxResults for Infoblox Provider

### ISSUE THREAD

**Issue by SelisNic** [openshift/external-dns-operator#221]
On the regular External-DNS helm chart there is an option to provide a maxResults setting at the Infoblox Provider.
Is it possible to provide it in the External-DNS Operator as well? We need this setting because we have more than 1000 objects in our Infoblox domain filter. (https://github.com/kubernetes-sigs/external-dns/pull/953). For now we are getting this error:

"Error": "AdmConProtoError: Result set too large (> 1000)"

**Comment by philipsabri** [comment]
We are having the same issue and are raising a ticket on redhat openshift support.

**Comment by candita** [comment]
Jira ticket raised.  Closing issue.
/close

**Comment by alebedev87** [comment]
Xref RFE: https://issues.redhat.com/browse/RFE-6132.
