### ISSUE TITLE
RFE-6560: Allow node placement policy customizations

### ISSUE THREAD

**Issue by raelga** [openshift/external-dns-operator#232]
Having the possibility to customize node placement policies such as tolerations, affinity and node selectors can improve the flexibility of the ExternalDNS deployment via the operator.

https://issues.redhat.com/browse/RFE-6560

Related to:

- https://issues.redhat.com/browse/RFE-5408
- https://github.com/openshift/external-dns-operator/issues/214
- https://github.com/openshift/external-dns-operator/issues/231

**Comment by alebedev87** [comment]
@raelga : we would need an RFE for such a change. Can you please file one?

**Comment by raelga** [comment]
RFE created: https://issues.redhat.com/browse/RFE-6560

**Comment by alebedev87** [comment]
The RFE takes over from here, closing the issue.
